version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - ps: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - ps: dotnet --version
build_script:
  - ps: .\build.ps1 -t Package
after_build:
  # For once the build has completed
artifacts:
 - path: '.\publish'
   name: Genopods
   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off