AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Genopods Cloudformation Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10


Resources:

    ApiFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./artifacts/ApiFunction.zip
            Handler: ApiFunction::ApiFunction.Function::FunctionHandlerAsync
            Runtime: dotnetcore2.0
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                GenopodsApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /toupper
                        Method: post

Outputs:

    GenopodsApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/toupper/"

    ApiFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt ApiFunction.Arn

    ApiFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt ApiFunctionRole.Arn
